language: cpp
services:
  - docker

script: |
  docker run --rm -it -v ${TRAVIS_BUILD_DIR}:/QnTools kreisl/rootcpp17:v6.20.04 /bin/bash -c '
  set -e # exit on failure
  set -x # trace for debug
  source /opt/rh/devtoolset-8/enable
  cd QnTools
  mkdir build
  cd build
  cmake ../ -DCMAKE_BUILD_TYPE=Debug
  make
  ctest'

branches:
  only:
  - master
